[package]
name = "inzoi_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"  # GUI
rfd = "0.15.0"     # File picker
axum = "0.8.3"     # Server
tokio = { version = "1.44.1", features = ["full"] }
serde_json = "1.0.140"
clap = { version = "4.5.20", features = ["derive"] }